### ISSUE TITLE
Error in `$<-.data.frame`

### ISSUE THREAD

**Issue by jyl6557** [mkshaw/r2mlm#56]
So I am working on the Lahman baseball database in R. I am trying to create a function that will count the all star appearances within the dataset.  I get an error where I am calling the function that I created but I have no idea why I am getting an error for the temporary dataframe that I have listed in the function. Any ideas on how to fix it?

library(Lahman)

all_star_df<-AllstarFull
batting_df<-Batting
people_df<-People
all_star_df<-na.omit(all_star_df)
batting_df<-na.omit(batting_df)
people_df<-na.omit(people_df)

count_all_star_appearances <- function(all_stars, batting){
  all_star_temp <- all_stars[ ,c('playerID', 'yearID')]
  all_star_temp$rookie_all_star_appearance <- "yes"
  batting <- merge(batting, all_star_temp, by=c('playerID', 'yearID'), all.x=TRUE)
  batting$rookie_all_star_appearance<-NA
  batting$rookie_all_star_appearance[is.na(batting$rookie_all_star_appearance)] <- "no"
  
  batting$rookie_id <- "yes"
  all_stars_non_rookie <- merge(all_stars, batting, by=c('playerID', 'yearID'), all.x=TRUE)
  all_stars_non_rookie$rookie_id[is.na(all_stars_non_rookie$rookie_id)] <- "no"
  all_stars_non_rookie <- all_stars_non_rookie[ which(all_stars_non_rookie$rookie_id == 'no'), ]
  
  all_stars_non_rookie <- all_stars_non_rookie[c('playerID')]
  all_stars_non_rookie <- as.data.frame(table(all_stars_non_rookie))
  colnames(all_stars_non_rookie) <- c('playerID', 'all_star')
  
  merged_df <- merge(batting, all_stars_non_rookie, by='playerID', all.x=TRUE)
  merged_df$all_star[merged_df$all_star > 0] <- "yes"
  merged_df$all_star[merged_df$all_star != 'yes'] <- "no"
  merged_df$all_star[is.na(merged_df$all_star)] <- "no"
  return(merged_df)
}

batting_df <- count_all_star_appearances(all_star_df, batting_df)

Here is the message:
Error in `$<-.data.frame`(`*tmp*`, "all_star", value = character(0)) : 
replacement has 0 rows, data has 2298

**Comment by mkshaw** [comment]
I can still help you, but just to confirm, this isn't related to the R package `r2mlm`, right? 

The issue you're having is related to NAs in your data. If you clear all the files in your environment by running the code `rm(list = ls()` and run your code again, does that fix the error?

I didn't get your error the first time, but if I run your code twice then there are multiple `rookie_all_star_appearance` variables after running line 13, `batting <- merge(batting, all_star_temp, by=c('playerID', 'yearID'), all.x=TRUE)`: `rookie_all_star_appearance.x` and `rookie_all_star_appearance.y`, which contain NAs that aren't handled in subsequent lines (because you weren't expecting these variables to exist).

**Comment by jyl6557** [comment]
> I can still help you, but just to confirm, this isn't related to the R package `r2mlm`, right?
> 
> The issue you're having is related to NAs in your data. If you clear all the files in your environment by running the code `rm(list = ls()` and run your code again, does that fix the error?
> 
> I didn't get your error the first time, but if I run your code twice then there are multiple `rookie_all_star_appearance` variables after running line 13, `batting <- merge(batting, all_star_temp, by=c('playerID', 'yearID'), all.x=TRUE)`: `rookie_all_star_appearance.x` and `rookie_all_star_appearance.y`, which contain NAs that aren't handled in subsequent lines (because you weren't expecting these variables to exist).

Hi, thank you for the reply:
This does not involved the r2mlm package at all. I have no idea what that does.
I did ran the code rm(list=ls()) and yet it doesn't work still. What's weird is that when I ran the batting_df <- count_all_star_appearances(all_star_df, batting_df) the first time in markdown, it successfulyl runs. But when I ran it again and again, it gives me that error message.

**Comment by mkshaw** [comment]
Right, so you're having a general R issue but you filed that as an issue on the GitHub for `r2mlm`, the R package that I wrote (note the URL we're on: github.com/mkshaw/r2mlm/issues). Your question is better suited to something like Stack Overflow, so I'm going to close this. The root of the issue is the NAs in your data. I'd suggest closing/clearing your R session and environment and running your code again.

**Comment by jyl6557** [comment]
Ok will do. How do I create a new issue on my own right here on Github?

**Comment by mkshaw** [comment]
GitHub issues are often for help with a specific package. For example, this is the GitHub for my R package `r2mlm`, so if people are using it and have problems or suggestions for improvement, they can make an issue here and I can try to help them with it. In your case, you're trying to write your own function using data from `Lahman`, but your issue isn't really about the `Lahman` package, it's about R more generally: merging data and getting an error. That's why Stack Overflow is probably the right place for your question. 

You can read about SO on Wikipedia [here](https://en.wikipedia.org/wiki/Stack_Overflow) and use it [here](https://stackoverflow.com/): it's free to post your question, but you should search your error there first (Google "Error in $<-.data.frame StackOverflow") to see if it has already been answered. If it hasn't been answered, then you can do what you did here: explain what you're trying to do and post your code. Just a warning that if you post a question that's been asked elsewhere, people can be a bit snarky about it, so make *sure* it hasn't been asked and answered elsewhere on StackOverflow first.

**Comment by jyl6557** [comment]
Ok thanks. I did google it and I tried those methods that I have seen on
stack overflow and yet it still doesn't help still. I Looked in the dataset
and there are no NA's for sure, even when I did na.omit. I was wondering if
you could still help me. My email is ***@***.*** I have already
posted on my own github repository page if you can see it.
https://github.com/jyl6557/lin3653/issues/1
 Thanks

*Jerry Lin*
*New Lenox, IL*
*Truman State University, 2019*
